version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wallet
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  # app:
  #   build: ./cmd/main
  #   ports:
  #     - "8080:8080"
  #   depends_on: 
  #     - postgres      